name: Build & Deploy (Local Build on Server)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # App env (stored as GitHub Secrets)
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # 1) STOP old containers before copying new app files
      - name: Stop running containers (compose down)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # port: 22
          script_stop: true
          script: |
            set -e
            # If this is the first deploy, the dir may not exist yet
            if [ -d /srv/caloriecounter/app ]; then
              cd /srv/caloriecounter/app
              docker compose down --remove-orphans
            fi

      # 2) COPY new version of the application
      - name: Sync files (rsync with delete)
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude ".env"
          path: ./
          remote_path: /srv/caloriecounter/app
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}


      # 3) Write/refresh .env and (re)start the stack
      - name: Build & run via SSH (compose up)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # port: 22
          script_stop: true
          envs: POSTGRES_USER,POSTGRES_PASSWORD,JWT_SECRET
          script: |
            set -euo pipefail
            # Write env used by compose (compose file should reference env_file: ../.env or similar)
            cat > /srv/caloriecounter/app/.env <<EOF
            POSTGRES_USER=${POSTGRES_USER}
            POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            JWT_SECRET=${JWT_SECRET}
            EOF
            chmod 600 /srv/caloriecounter/app/.env

            cd /srv/caloriecounter/app

            # Optional: refresh public images for DB/cache, etc.
            docker compose pull || true
            # Build local images from your Dockerfile(s)
            docker compose build --pull
            # Start in background
            docker compose up -d --remove-orphans

            # Optional: reclaim disk
            docker image prune -af || true

            docker compose ps
